/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

/**
 *
 * @author x18119999
 */
public class CreateAccountPanel extends javax.swing.JPanel {

    private BankApplication bankApplication;
    
    /**
     * Creates new form CreateAccountPanel
     */
    public CreateAccountPanel() {
        initComponents();
        accountIdLabel.setVisible(false);
        pinLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        accountIdLabel = new javax.swing.JLabel();
        pinLabel = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        stdAccountButton = new javax.swing.JButton();
        businessAccountButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Bank Application");

        accountIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        accountIdLabel.setText("Your account ID is:");

        pinLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pinLabel.setText("Your PIN is:");

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        stdAccountButton.setText("Standard");
        stdAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdAccountButtonActionPerformed(evt);
            }
        });

        businessAccountButton.setText("Business");
        businessAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pinLabel)
                            .addComponent(accountIdLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(stdAccountButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(businessAccountButton)
                        .addGap(0, 221, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(returnButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(accountIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pinLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdAccountButton)
                    .addComponent(businessAccountButton))
                .addGap(32, 32, 32)
                .addComponent(returnButton)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        bankApplication.hideCreateAccountPanel();
        accountIdLabel.setVisible(false);
        pinLabel.setVisible(false);

        bankApplication.showStartupPanel();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void stdAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdAccountButtonActionPerformed
        StandardAccount account = new StandardAccount();
        accountIdLabel.setText("Your account ID is: " + account.getAccountNumber());
        pinLabel.setText("Your PIN is: " + account.getPin());
        accountIdLabel.setVisible(true);
        pinLabel.setVisible(true);

        bankApplication.getBank().addAccount(account);
        bankApplication.getBank().printAccounts();
    }//GEN-LAST:event_stdAccountButtonActionPerformed

    private void businessAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessAccountButtonActionPerformed
        BusinessAccount account = new BusinessAccount();
        accountIdLabel.setText("Your account ID is: " + account.getAccountNumber());
        pinLabel.setText("Your PIN is: " + account.getPin());
        accountIdLabel.setVisible(true);
        pinLabel.setVisible(true);

        bankApplication.getBank().addAccount(account);
        bankApplication.getBank().printAccounts();
    }//GEN-LAST:event_businessAccountButtonActionPerformed

    public void setParent(BankApplication bankApplication) {
        // Links the parent object to this panel to allow access to the rest of the program.
        this.bankApplication = bankApplication;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountIdLabel;
    private javax.swing.JButton businessAccountButton;
    private javax.swing.JLabel pinLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton stdAccountButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
