/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

/**
 *
 * @author x18119999
 */
public class MainPanel extends javax.swing.JPanel {

    private BankApplication bankApplication;
    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();   
        errorLabel.setVisible(false);
    }
    
    public void setBalanceLabel() {
        Account loggedInAccount = bankApplication.getBank().getLoggedIn();
        balanceLabel.setText("€" + Double.toString(loggedInAccount.getBalance()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        balanceFixedLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        withdrawButton = new javax.swing.JButton();
        depositButton = new javax.swing.JButton();
        withdrawField = new javax.swing.JTextField();
        depositField = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Bank Application");

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        balanceFixedLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        balanceFixedLabel.setText("Balance:");

        balanceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        balanceLabel.setText("                ");

        withdrawButton.setText("Withdraw");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });

        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        errorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 51, 0));
        errorLabel.setText("Please enter a number only");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(balanceFixedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(balanceLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(withdrawField)
                                    .addComponent(withdrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(depositButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(depositField)))
                            .addComponent(logoutButton)
                            .addComponent(errorLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceFixedLabel)
                    .addComponent(balanceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawButton)
                    .addComponent(depositButton))
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        bankApplication.getBank().logout();
        bankApplication.hideMainPanel();
        errorLabel.setVisible(false);
        withdrawField.setText("");
        depositField.setText("");

        bankApplication.showStartupPanel();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        Account loggedInAccount = bankApplication.getBank().getLoggedIn();
        double balance = loggedInAccount.getBalance();
        double withdrawAmount = 0;

        try {
            withdrawAmount = Double.parseDouble(withdrawField.getText());
        } catch(NumberFormatException e) {
            errorLabel.setText("Please enter a number only");
            errorLabel.setVisible(true);
        }

        
        if (balance >= withdrawAmount) {
            loggedInAccount.withdraw(withdrawAmount);
            setBalanceLabel();
        } else {
            errorLabel.setText("Insufficient funds");
            errorLabel.setVisible(true);
        }
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        Account loggedInAccount = bankApplication.getBank().getLoggedIn();

        try {
            loggedInAccount.deposit(Double.parseDouble(depositField.getText()));
        } catch (NumberFormatException e) {
            errorLabel.setText("Please enter a number only");
            errorLabel.setVisible(true);
        }

        setBalanceLabel();
    }//GEN-LAST:event_depositButtonActionPerformed

    public void setParent(BankApplication bankApplication) {
        // Links the parent object to this panel to allow access to the rest of the program.
        this.bankApplication = bankApplication;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceFixedLabel;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JButton depositButton;
    private javax.swing.JTextField depositField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton withdrawButton;
    private javax.swing.JTextField withdrawField;
    // End of variables declaration//GEN-END:variables
}
